= LostItem(분실물)
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[lostitem-create-lostitem]]
== 분실물 생성

operation::lostitem-create-lostitem[snippets='http-request,request-headers,request-fields,http-response,response-fields']


[[lostitem-search]]
== 분실물 리스트 조회(검색)

operation::lostitem-search[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[lostitem-get-my-list]]
== 내가 쓴 글 (분실물)

operation::lostitem-get-my-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[lostitem-get-detail]]
== 분실물 상세 조회

operation::lostitem-get-detail[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[lostitem-delete-lostitem]]
== 분실물 삭제

operation::lostitem-delete-lostitem[snippets='http-request,request-headers,path-parameters,http-response']


[[lostitem-edit-lostitem]]
== 분실물 수정

operation::lostitem-edit-lostitem[snippets='http-request,request-headers,path-parameters,request-fields,http-response']
