= Member(회원)
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[member-get-nickname-duplicate]]
== 회원 닉네임 중복 확인

operation::member-get-nickname-duplicate[snippets='http-request,request-headers,request-headers,query-parameters,http-response,response-fields']

[[member-signup]]
== 회원 생성

operation::member-signup[snippets='http-request,request-headers,request-fields,http-response,response-fields']


[[member-get-member-detail]]
== 회원 상세 조회

operation::member-get-member-detail[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[member-edit-member]]
== 회원 수정

operation::member-edit-member[snippets='http-request,request-headers,request-fields,http-response']


[[member-get-recruitment-list]]
== My 모집 리스트 조회

operation::member-get-recruitment-list[snippets='http-request,request-headers,path-parameters,query-parameters,http-response,response-fields-content']


[[member-get-participation-list]]
== My 참여 리스트 조회

operation::member-get-participation-list[snippets='http-request,request-headers,path-parameters,query-parameters,http-response,response-fields-content']


[[member-get-my-show-review-list]]
== 내가 쓴 글 (한 줄 리뷰)

operation::member-get-my-show-review-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[member-get-my-lost-item-list]]
== 내가 쓴 글 (분실물)

operation::member-get-my-lost-item-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[member-delete-member]]
== 회원 탈퇴

operation::member-delete-member[snippets='http-request,request-headers,request-fields,http-response']
