= Party(파티)
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[party-get-party-list]]
== 파티 리스트 조회

operation::party-get-party-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[party-search]]
== 파티 검색

operation::party-search[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']


[[party-get-party-detail]]
== 파티 상세 조회

operation::party-get-party-detail[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[party-create-party]]
== 파티 생성

operation::party-create-party[snippets='http-request,request-headers,request-fields,http-response,response-fields']


[[party-delete-party]]
== 파티 삭제

operation::party-delete-party[snippets='http-request,request-headers,path-parameters,http-response']


[[party-edit-party]]
== 파티 수정

operation::party-edit-party[snippets='http-request,request-headers,request-fields,http-response']


[[party-participate-party]]
== 파티 참여

operation::party-participate-party[snippets='http-request,request-headers,path-parameters,http-response']


[[party-get-participated]]
== 파티 참여 여부

operation::party-get-participated[snippets='http-request,request-headers,query-parameters,http-response,response-fields-content']
